config/routes.rb
Rails.application.routes.draw do

use_doorkeeper
get 'matters/:id/timeline' => 'matters#timeline', as: :matter_timeline
post 'api/registrations' => 'api/registrations#create'
root 'dashboard#dashboard'
get 'dashboard' => 'dashboard#dashboard', as: :dashboard

#Sessions
get 'sign_in' => 'sessions#new', as: :sign_in
post 'sign_in' => 'sessions#create'
delete 'sign_in' => 'sessions#delete', as: :end_session
get 'sign_out' => 'sessions#delete', as: :sign_out

get '/matters/:id/client_dashboard' => 'dashboard#client_dashboard', as: :client_dashboard

resources :roles
resources :firm
resources :user_matters
resources :users


resources :matters do
  resources :events
  resources :people
  resources :docs do
    resources :client_comments
    resources :attorney_comments
    resources :law_office_comments
  end
end

namespace :api do
  resources :matters do
    resources :events
  end
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attorney_comment.rb
class AttorneyComment < ApplicationRecord
  belongs_to :doc
end

app/models/client_comment.rb
class ClientComment < ApplicationRecord
  belongs_to :doc
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :matter
  attachment :doc, destroy: false, extension: "pdf"
  has_many :users
  has_many :client_comments
  has_many :attorney_comments
  has_many :law_office_comments
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :matters
  has_many :docs
  MONTH = ['-','01','02','03','04','05','06','07','08','09','10','11','12']
  DAY = ['-','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
  HOUR = ['-','00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24']
  MINUTE =['-','00','05','10','15','20','25','30','35','40','45','50','55']
end

app/models/firm.rb
class Firm < ApplicationRecord

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :matter
end

app/models/matter.rb
class Matter < ApplicationRecord

  has_many :users, through: :user_matters
  has_many :user_matters

  has_many :docs
  has_many :events
  has_many :attorney_comments, through: :docs
  has_many :client_comments, through: :docs
  has_many :law_office_comments, through: :docs

  validates :year, presence: true

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :matter
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :matters, through: :user_matters
  has_many :user_matters
  ROLE = ['Attorney', 'Client', 'Admin', 'Paralegal']
  include Gravtastic
  gravtastic
end

app/models/user_matter.rb
class UserMatter < ApplicationRecord
  belongs_to :matter
  belongs_to :user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
before_action do
  require_login!
end

  def hello
    @users = User.all
    @matters = Matter.all
    @user_matters = UserMatter.all
    @roles = Role.all
  end

  def dashboard
    @users = User.all
    @matters = Matter.all
    @user_matters = UserMatter.all
    @roles = Role.all
  end

  def client_dashboard
    @matter = Matter.find(params[:id])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/firm_helper.rb
module FirmHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/client_dashboard.html.erb
<h1>Dashboard</h1>


<h3>Events </h3>
<h3>Inventory</h3>
<h3>People </h3>

<h3>All Documents </h3>
<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Document ID</th>
      <th>Status</th>
      <th>Date</th>
      <th>Title</th>
      <th>Link</th>

    </tr>
  </thead>
  <tbody>
    <% @matter.documents do |document|%>
      <tr>
        <td><%=document.id%> </td>
        <td><%=document.status%> </td>
        <td><%=document.date%></td>
        <td><%=document.title%></td>
        <td><%= link_to "See Detail", document_path(id: document.id) %></td>
      </tr>
    <%end%>
    </tr>
  </tbody>
</table>

app/views/dashboard/dashboard.html.erb
<h1>Dashboard</h1>

<h5>LINKS</h5>
  <ul>
    <li><%= link_to "Create User", new_user_path%></li>
    <li><%= link_to "Create Matter", new_matter_path%></li>
    <li><%= link_to "Create User Matter", new_user_matter_path%></li>
  </ul>

  <h3>All Matters</h3>
      <table class="mdl-data-table mdl-js-data-table">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Matter ID</th>
            <th>Type</th>
            <th>Status</th>
            <th>Kind</th>
            <th>Opposing Party</th>
            <th>Opposing Counsel</th>
            <th>Court</th>
            <th>Judge</th>
            <th>Detail</th>
          </tr>
        </thead>
        <tbody>
          <% @matters.each do |matter|%>
            <tr>
            <td><%=matter.id%> </td>
            <td><%=matter.cause_number%> </td>
            <td><%=matter.status%> </td>
            <td><%=matter.kind%></td>
            <td><%=matter.opposing_party%></td>
            <td><%=matter.opposing_counsel%></td>
            <td><%=matter.court%></td>
            <td><%=matter.judge%></td>
            <td><%=link_to "Detail", matter_path(id: matter.id)%></td>
            </tr>
          <%end%>
          </tr>
        </tbody>
      </table>


<h4>All Users</h4>
  <table class="mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th>User ID </th>
        <th class="mdl-data-table__cell--non-numeric">Username</th>
        <th>Email</th>
        <th>First Name </th>
        <th>Middle Name </th>
        <th>Last Name </th>

      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
        <tr>
        <td> <%=user.id%></td>
        <td>  <%=user.username%> </td>
        <td> <%=user.email%> </td>
        <td> <%=user.first_name%> </td>
        <td> <%=user.middle_name%> </td>
        <td> <%=user.last_name%> </td>
        </tr>
      <%end%>
      </tr>
    </tbody>
  </table>
<h3>All User-Matters</h3>
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">User</th>
          <th>Matter</th>
        </tr>
      </thead>
      <tbody>
        <% @user_matters.each do |user_matter|%>
          <tr>
          <td>  <%=user_matter.matter_id%> </td>
          <td> <%=user_matter.user_id%> </td>
          </tr>
        <%end%>
        </tr>
      </tbody>
    </table>

app/views/dashboard/hello.html.erb
<h1>Dashboard</h1>

<h5>LINKS</h5>
  <ul>
    <li><%= link_to "Create User", new_user_path%></li>
    <li><%= link_to "Create Matter", new_matter_path%></li>
    <li><%= link_to "Create UserMatter", new_user_matter_path%></li>
  </ul>

<h4>All Users</h4>
  <table class="mdl-data-table mdl-js-data-table">
    <thead>
      <tr>
        <th>User ID </th>
        <th class="mdl-data-table__cell--non-numeric">Username</th>
        <th>Email</th>
        <th>First Name </th>
        <th>Middle Name </th>
        <th>Last Name </th>

      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
        <tr>
        <td> <%=user.id%></td>
        <td>  <%=user.username%> </td>
        <td> <%=user.email%> </td>
        <td> <%=user.first_name%> </td>
        <td> <%=user.middle_name%> </td>
        <td> <%=user.last_name%> </td>

        </tr>
      <%end%>
      </tr>
    </tbody>
  </table>
<h3>All User-Matters</h3>
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">User</th>
          <th>Matter</th>
        </tr>
      </thead>
      <tbody>
        <% @user_matters.each do |user_matter|%>
          <tr>
          <td>  <%=user_matter.matter_id%> </td>
          <td> <%=user_matter.user_id%> </td>
          </tr>
        <%end%>
        </tr>
      </tbody>
    </table>
<h3>All Matters</h3>
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Matter ID</th>
          <th>Type</th>
          <th>Status</th>
          <th>Kind</th>
          <th>Opposing Party</th>
          <th>Opposing Counsel</th>
          <th>Court</th>
          <th>Judge</th>
        </tr>
      </thead>
      <tbody>
        <% @matters.each do |matter|%>
          <tr>
          <td><%=matter.id%> </td>
          <td><%=matter.cause_number%> </td>
          <td><%=matter.status%> </td>
          <td><%=matter.kind%></td>
          <td><%=matter.opposing_party%></td>
          <td><%=matter.opposing_counsel%></td>
          <td><%=matter.court%></td>
          <td><%=matter.judge%></td>
          </tr>
        <%end%>
        </tr>
      </tbody>
    </table>

<h3>All Documents </h3>
<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Document ID</th>
      <th>Status</th>
      <th>Date</th>
      <th>Title</th>
      <th>Link</th>

    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document|%>
      <tr>
        <td><%=document.id%> </td>
        <td><%=document.status%> </td>
        <td><%=document.date%></td>
        <td><%=document.title%></td>
        <td><%= link_to "See Detail", document_path(id: document.id) %></td>
      </tr>
    <%end%>
    </tr>
  </tbody>
</table>

app/views/dashboard/welcome.html.erb
<h1>Swift Discovery</h1>

<h5>LINKS</h5>
  <ul>
    <li><%= link_to "Create User", new_user_path%></li>
    <li><%= link_to "Create Matter", new_matter_path%></li>
    <li><%= link_to "Create UserMatter", new_user_matter_path%></li>
    <li><%= link_to "Dashboard", dashboard_path%></li>
  </ul>