config/routes.rb
Rails.application.routes.draw do

use_doorkeeper
get 'matters/:id/timeline' => 'matters#timeline', as: :matter_timeline
post 'api/registrations' => 'api/registrations#create'
root 'dashboard#dashboard'
get 'dashboard' => 'dashboard#dashboard', as: :dashboard

#Sessions
get 'sign_in' => 'sessions#new', as: :sign_in
post 'sign_in' => 'sessions#create'
delete 'sign_in' => 'sessions#delete', as: :end_session
get 'sign_out' => 'sessions#delete', as: :sign_out

get '/matters/:id/client_dashboard' => 'dashboard#client_dashboard', as: :client_dashboard

resources :roles
resources :firm
resources :user_matters
resources :users


resources :matters do
  resources :events
  resources :people
  resources :docs do
    resources :client_comments
    resources :attorney_comments
    resources :law_office_comments
  end
end

namespace :api do
  resources :matters do
    resources :events
  end
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attorney_comment.rb
class AttorneyComment < ApplicationRecord
  belongs_to :doc
end

app/models/client_comment.rb
class ClientComment < ApplicationRecord
  belongs_to :doc
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :matter
  attachment :doc, destroy: false, extension: "pdf"
  has_many :users
  has_many :client_comments
  has_many :attorney_comments
  has_many :law_office_comments
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :matters
  has_many :docs
  MONTH = ['-','01','02','03','04','05','06','07','08','09','10','11','12']
  DAY = ['-','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
  HOUR = ['-','00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24']
  MINUTE =['-','00','05','10','15','20','25','30','35','40','45','50','55']
end

app/models/firm.rb
class Firm < ApplicationRecord

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :matter
end

app/models/law_office_comment.rb
class LawOfficeComment < ApplicationRecord
  belongs_to :doc
end

app/models/matter.rb
class Matter < ApplicationRecord

  has_many :users, through: :user_matters
  has_many :user_matters

  has_many :docs
  has_many :events
  has_many :attorney_comments, through: :docs
  has_many :client_comments, through: :docs
  has_many :law_office_comments, through: :docs

  validates :year, presence: true

end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :matter
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :matters, through: :user_matters
  has_many :user_matters
  ROLE = ['Attorney', 'Client', 'Admin', 'Paralegal']
  include Gravtastic
  gravtastic
end

app/models/user_matter.rb
class UserMatter < ApplicationRecord
  belongs_to :matter
  belongs_to :user
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action do
      require_login!
    end

    def new
      @matter = Matter.find(params[:matter_id])
      @doc = @matter.docs.create(document_params)
    end

    def create
      @matter = Matter.find(params[:matter_id])
      @doc = @matter.docs.create(document_params)
      if @doc.save
        redirect_to matter_path(@matter), notice: "Document Created"
      else
        render :new
      end
    end


def edit
  @doc = @matter.doc(document_params)
end
    def update
      @docs = @matter.docs(document_params)
      @doc = @matter.doc(:id)
      if @doc.save
        redirect_to matter_path(@matter), notice: "Document Updated"
      else
        render :edit
      end
    end

    def index
      @matter = Matter.find(params[:matter_id])
      @docs = @matter.docs.all
    end

    def show
      @matter = Matter.find(params[:matter_id])
      @doc = @matter.docs.find(params[:id])
      @docs = @matter.docs.all
    end


    private

    def document_params
      params.require(:doc).permit(:doc, :matter_id, :users, :status, :title, :year,  :attorney_notes, :client_notes, :date, :description, :paralegal_notes, :doc_id,  :user_ids => [] )
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/firm_helper.rb
module FirmHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/docs/_client_comment.html.erb
<h6>Client Comment:</h6>
<%@doc.client_comments.each do |client_comment|%>
  <%=client_comment.comment%>
<%end%>
<%= form_for([@matter, @matter.docs,  @doc.client_comments.build]) do |f| %>
<%= f.label :comment%>
 <%= f.text_area :comment %>
    <%= f.submit %>
<% end %>

app/views/docs/_upload.html.erb
<% if @matter.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @matter.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </div>
<% end %>




<%= form_for([@matter, @matter.docs.build]) do |f| %>

  <%= f.label :title%>
   <%= f.text_field :title %> </br>
   <%= f.label :status%>
   <%= f.text_field :status %></br>
   <%= f.label :description%>
   <%= f.text_field :description %></br>
   <%= f.label :date%>
   <%= f.text_field :date%>
  <%= f.file_field :doc, as: :file %>
    <%= f.submit %>
<% end %>

app/views/docs/index.html.erb
<h3>All Documents </h3>
<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Document ID</th>
      <th>Status</th>
      <th>Date</th>
      <th>Title</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% @docs.each do |doc|%>
      <tr>
        <td><%=doc.id%> </td>
        <td><%=doc.status%> </td>
        <td><%=doc.date%></td>
        <td><%=doc.title%></td>
        <td><%=link_to 'Detail', matter_doc_path(id: doc.id)%></td>
      </tr>
    <%end%>
    </tr>
  </tbody>
</table>

app/views/docs/show.html.erb
<h1><%= @doc.title%></h1>
<table class="mdl-data-table mdl-js-data-table">
  <tr>
    <th>
      Doc Id
    </th>
    <th>
      Status
    </th>
    <th>
      Date
    </th>
    <th>
      Title
    </th>
  </tr>
  <tr>
    <th>
    <%=@doc.id%>
    </th>
    <th>
      <%=@doc.status%>
    </th>
    <th>
      <%=@doc.date%>
    </th>
    <th>
      <%=@doc.title%>
    </th>
  </tr>
</table>


<iframe src="<%= attachment_url(@doc, :doc, format: 'pdf') %>" width="400px" height="600px"></iframe>

<h5>Client Commment</h5>
<%= render partial: 'client_comment'%>

<div class="mdl-layout__content">
  <div class="mdl-page-content">
    <h5>Upload Document</h5>
    <%= render partial: 'upload'%>
  </div>
</div>